### ISSUE TITLE
Errors in iOS app  Xcode Version 15.1 (15C65)

### ISSUE THREAD

**Issue by Jahagirds** [gev2002/react-native-vision-camera-image-labeler#2]
I'm getting an error on the iOS app while running the app with XCODE. Please help me to resolve this issue 

 "react-native-vision-camera": "^4.0.4",
 "react-native-vision-camera-image-labeler": "^1.0.0",
 "react-native-worklets-core": "^1.2.0",

![Screenshot 2024-05-21 at 16 45 22](https://github.com/gev2002/react-native-vision-camera-image-labeler/assets/147040668/f5140c85-7dee-49c0-853a-a31d943564d9)

**Comment by stevengoldberg** [comment]
I got these errors when I tried building my app without having installed `react-native-worklets-core`.

I'm using worklets-core 1.3.3 and compiled successfully.

**Comment by Jahagirds** [comment]
HI @stevengoldberg  I'm still getting these errors with this code, Can you correct me if I'm doing something wrong? I'm sharing my code 
File: VisionCameraImageLabeler.swift

 "react-native-vision-camera": "^4.0.4",
    "react-native-vision-camera-image-labeler": "^1.0.0",
    "react-native-worklets-core": "^1.3.3",
    
    
   

My code: 

import Foundation
import VisionCamera
import MLKitVision
import MLKitImageLabeling



@objc(VisionCameraImageLabeler)
public class VisionCameraImageLabeler: FrameProcessorPlugin {
    public override init(proxy: VisionCameraProxyHolder, options: [AnyHashable: Any]! = [:]) {
        super.init(proxy: proxy, options: options)
        let minConfidence = options["minConfidence"]!
        if let minConfidence = minConfidence as? Double, minConfidence > 0 {
            labelerOptions.confidenceThreshold = (minConfidence) as NSNumber
        }
    }
    private let labelerOptions = ImageLabelerOptions();
    public override func callback(
        _ frame: Frame,
        withArguments arguments: [AnyHashable: Any]?
    ) -> Any {
        var data:[Any] = []
        let buffer = frame.buffer
        let image = VisionImage(buffer: buffer);
        image.orientation = getOrientation(orientation: frame.orientation)
        let labeler = ImageLabeler.imageLabeler(options: labelerOptions);
        let dispatchGroup = DispatchGroup()
        dispatchGroup.enter()
        labeler.process(image) { labels, error in
            defer {
                dispatchGroup.leave()
            }
            guard error == nil, let labels = labels else { return }
            for label in labels {
            var obj : [String:Any] = [:]
            let labelText = label.text
            let confidence = label.confidence
                obj["label"] = labelText
                obj["confidence"] = confidence
                data.append(obj)
            }
        }
        dispatchGroup.wait()

        return data
    }
    private func getOrientation(
        orientation: UIImage.Orientation
      ) -> UIImage.Orientation {
        switch orientation {
          case .right, .leftMirrored:
            return .up
          case .left, .rightMirrored:
            return .down
          case .up, .downMirrored:
            return .left
          case .down, .upMirrored:
            return .right
        default:
            return .up
        }
      }

}

**Comment by gev2002** [comment]
This is problem with cache clean all cache which you can delete and reinstall modules  and will be Ok).

**Comment by Jahagirds** [comment]
> This is problem with cache clean all cache which you can delete and reinstall modules and will be Ok).

@gev2002 Thanks for the reply.

I have done all the processes that you have mentioned in the comment.
I am still facing the same issue.

**Comment by gev2002** [comment]
Are you tried, clean cache of Xcode from Settings -> Storage ?
