### ISSUE TITLE
node_modules/react-native-vision-camera-image-labeler/android/src/main/java/com/visioncameraimagelabeler/VisionCameraImageLabelerPackage.kt:14:7 Unresolved reference: FrameProcessorPluginRegistry

### ISSUE THREAD

**Issue by shishi-RN** [gev2002/react-native-vision-camera-image-labeler#7]
node_modules/react-native-vision-camera-image-labeler/android/src/main/java/com/visioncameraimagelabeler/VisionCameraImageLabelerPackage.kt:14:7 Unresolved reference: FrameProcessorPluginRegistry

How to resolve this?

**Comment by gev2002** [comment]
You can use vision-camera version 4.3.2 for now, it because vision-camera updated to 4.5 and my plugin now can't support it I'll update it when have free time.

**Comment by shishi-RN** [comment]
Hi, I encountered another issue while launching the app. It crashes when opening the camera, but the app works when isActive={false}

**Comment by gev2002** [comment]
Are you using, my plugin like I show in README ? I tested again and don't find any problems it works any vision-camera above 4.3.2.
